// POST http://172.17.1.180/api/mobile/insert-upah-tenaga-kerja
// POST http://sugarcane.sblampung.com/api/mobile/insert-upah-tenaga-kerja
POST http://localhost/tebu/public/api/mobile/insert-upah-tenaga-kerja
Content-Type: application/json
Authorization: Bearer 2|P6KBDbgXNTqLBGF9SAZjg2ewRFPLv2FWp5rKhs2O55bc9120

{
  "companycode": "TBL1",
  "lkhno": "LKH15120325-2",
  "tenagakerjaid": "M1234",
  "tenagakerjaurutan": 1,
  "activitycode": "4.4.3",
  "jenistenagakerja": 4,
  "lkhdate": "2025-12-15",
  "jammulai": "07:00:00",
  "jamselesai": "15:00:00",
  "overtimehours": 0
}