// POST http://172.17.1.180/api/mobile/insert-upah-tenaga-kerja
// POST http://sugarcane.sblampung.com/api/mobile/insert-upah-tenaga-kerja
POST http://localhost/tebu/public/api/mobile/insert-upah-tenaga-kerja
Content-Type: application/json
Authorization: Bearer 2|6BQGCVlrhymLd4wbb08fWpJlFyHL0bX9GQcBQRni34cec752

{
  "companycode": "TBL1",
  "lkhno": "LKH29090325-1",
  "tenagakerjaid": "M0028",
  "tenagakerjaurutan": 0,
  "activitycode": "V.5.2.4",
  "jenistenagakerja": 1,
  "lkhdate": "2025-09-29",
  "jammulai": "07:00:00",
  "jamselesai": "15:00:00",
  "overtimehours": 0
}